version: '3'
services:
    kevbot:
        build: .
        image: vgroove/kevbot
        container_name: 'kevbot'
        volumes:
            - ./kevbot:/app/kevbot
        depends_on:
            - mongodb
    mongodb:
        image: mongo:3.4
        container_name: 'mongodb'
        environment:
            - MONGO_DATA_DIR=/data/db
        volumes:
            - /var/lib/mongodb:/data/db
